Repository linagora/james-project, pull requests merged in 2018-07, with the labels that each got.

#1538 JAMES-2464 ConcurrentTestRunner should use a builder
  mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxMapperConcurrencyTest.java
  mailbox/plugin/quota-mailing/src/test/java/org/apache/james/mailbox/quota/mailing/listeners/QuotaThresholdMailingIntegrationTest.java
  mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageIdMapperTest.java
  mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMapperTest.java
  mailbox/tika/src/test/java/org/apache/james/mailbox/tika/CachingTextExtractorTest.java
  protocols/imap/src/test/java/org/apache/james/imap/processor/base/UidMsnConverterTest.java
  protocols/smtp/src/test/java/org/apache/james/protocols/smtp/AbstractSMTPServerTest.java
  server/container/guice/guice-common/src/test/java/org/apache/james/utils/InMemoryMailRepositoryStoreTest.java
  server/container/util/src/main/java/org/apache/james/util/concurrency/ConcurrentTestRunner.java
  server/container/util/src/test/java/org/apache/james/util/concurrency/ConcurrentTestRunnerTest.java
  server/data/data-api/src/test/java/org/apache/james/mailrepository/api/MailRepositoryUrlStoreContract.java
  server/mailrepository/mailrepository-api/src/test/java/org/apache/james/mailrepository/MailRepositoryContract.java
  server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/ProvisioningTest.java
  server/protocols/jmap/src/test/java/org/apache/james/jmap/DefaultMailboxesProvisioningFilterTest.java
Labels: enhancement

#1546 MPT-42 Fasten MPT deployment tests
  mpt/core/pom.xml
  mpt/core/src/main/java/org/apache/james/mpt/helper/ScriptBuilder.java
  mpt/core/src/main/java/org/apache/james/mpt/host/ExternalHostSystem.java
  mpt/core/src/main/java/org/apache/james/mpt/session/ExternalSession.java
  mpt/impl/imap-mailbox/external-james/pom.xml
  mpt/impl/imap-mailbox/external-james/src/test/java/org/apache/james/mpt/imapmailbox/external/james/DeploymentValidation.java
  mpt/impl/imap-mailbox/external-james/src/test/java/org/apache/james/mpt/imapmailbox/external/james/JamesDeploymentValidation.java
  mpt/impl/imap-mailbox/external-james/src/test/java/org/apache/james/mpt/imapmailbox/external/james/host/ExternalJamesHostSystem.java
  mpt/impl/imap-mailbox/external-james/src/test/resources/org.apache.james.imap.scripts/ValidateDeployment.test
Labels: build-time

#1581 JAMES-2304 JDBC Mail repository do not allow content update.
  server/data/data-jdbc/src/test/java/org/apache/james/mailrepository/jdbc/JDBCMailRepositoryTest.java
Labels: contribution
