Repository linagora/james-project, pull requests merged in 2019-11, with the labels that each got.

#2825 JAMES-2966 bump elastic metrics reporter version to avoid thread leaks
  pom.xml
Labels: waiting_merge

#2867 One fix per day #4
  server/data/data-jdbc/src/main/java/org/apache/james/mailrepository/jdbc/JDBCMailRepository.java
Labels: refactoring, waiting_merge

#2895 JAMES-2949 Fix metric reporting upon dequeue
  server/mailet/mailetcontainer-camel/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailSpooler.java
  server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java
Labels: bug

#2921 JAMES-2937 Calling several time the RabbitMQ endpoint should not fail
  backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/ReactorRabbitMQChannelPool.java
  backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQHealthCheckTest.java
  server/protocols/webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/WebAdminServerIntegrationTest.java
Labels: bug
