Repository linagora/james-project, pull requests merged in 2019-07, with the labels that each got.

#2490 JAMES-2782 LinShare now escapes HTML characters
  third-party/linshare/src/test/resources/backend/Dockerfile
Labels: build-stability, waiting_merge

#2547 JAMES-XXXX Fix usage of TemporaryFolder in tests
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/AddDeliveredToHeaderTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/BounceIntegrationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/CommonMailetConfigurationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/DKIMIntegrationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/DirectResolutionRemoteDeliveryIntegrationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/GatewayRemoteDeliveryIntegrationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/MailetErrorsTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/NetworkMatcherIntegrationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/RecipientRewriteTableIntegrationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/SieveDelivery.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/SmtpAuthIntegrationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/TemporaryJamesServer.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/crypto/SMIMEDecryptIntegrationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/mailets/crypto/SMIMESignIntegrationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpAuthorizedAddressesTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpBracketEnforcementTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpContentTypeTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpIdentityVerificationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpNullSenderTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpRandomStoringTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpSizeLimitationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/AddFooterTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/AliasMappingTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/AmqpForwardAttachmentTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/ContactExtractorTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/DlpIntegrationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/DomainMappingTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/GroupMappingRelayTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/GroupMappingTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/ICSAttachmentWorkflowTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/IsOverQuotaMatcherTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/MailReprocessingIntegrationTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/SpamAssassinTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/StripAttachmentTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/ToRepositoryTest.java
  server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/ToSenderDomainRepositoryTest.java
Labels: waiting_merge

#2543 [CI_ONLY] JAMES-2735 Update mailet and matcher that uses the headers and the per
  mailet/standard/src/main/java/org/apache/james/transport/mailets/RemoveMimeHeader.java
  mailet/standard/src/main/java/org/apache/james/transport/mailets/RemoveMimeHeaderByPrefix.java
  mailet/standard/src/main/java/org/apache/james/transport/matchers/HasHeader.java
  mailet/standard/src/main/java/org/apache/james/transport/matchers/HasHeaderWithPrefix.java
  mailet/standard/src/test/java/org/apache/james/transport/mailets/RemoveMimeHeaderByPrefixTest.java
  mailet/standard/src/test/java/org/apache/james/transport/mailets/RemoveMimeHeaderTest.java
  mailet/standard/src/test/java/org/apache/james/transport/matchers/HasHeaderTest.java
  mailet/standard/src/test/java/org/apache/james/transport/matchers/HasHeaderWithPrefixTest.java
Labels: contribution, no_review
