Repository linagora/james-project, pull requests merged in 2019-06, with the labels that each got.

#2424 JAMES-2767 Use an existing ElasticSearch image in the readme
  README.adoc
Labels: Documentation

#2444 JAMES-1902 Avoid creating the SPOOL MailQueue upon injection
  server/container/guice/mailet/src/main/java/org/apache/james/modules/server/CamelMailetContainerModule.java
  server/mailet/mailetcontainer-camel/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailetContext.java
  server/mailet/mailetcontainer-camel/src/test/java/org/apache/james/mailetcontainer/impl/JamesMailetContextTest.java
Labels: build-stability

#2447 JAMES-2630 Use an elastic scheduler for byte reading
  server/blob/blob-api/src/main/java/org/apache/james/blob/api/Store.java
Labels: build-stability, waiting_merge

#2458 JAMES-2767 prevent import of commons-logging to make log go through s…
  backends-common/elasticsearch/pom.xml
Labels: waiting_merge

#2455 Improve ES container methods semantic
  backends-common/elasticsearch/src/test/java/org/apache/james/backends/es/DockerElasticSearch.java
  backends-common/elasticsearch/src/test/java/org/apache/james/backends/es/DockerElasticSearchRule.java
  mailbox/plugin/quota-search-elasticsearch/src/test/java/org/apache/james/quota/search/elasticsearch/ElasticSearchQuotaSearchTestSystemExtension.java
  mpt/impl/imap-mailbox/elasticsearch/src/test/java/org/apache/james/mpt/imapmailbox/elasticsearch/host/ElasticSearchHostSystem.java
  server/container/guice/cassandra-guice/src/test/java/org/apache/james/DockerElasticSearchExtension.java
  server/container/guice/cassandra-guice/src/test/java/org/apache/james/DockerElasticSearchRule.java
  server/container/metrics/metrics-es-reporter/src/test/java/org/apache/james/metric/es/DockerElasticSearchExtension.java
  server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraStepdefs.java
  server/protocols/jmap-integration-testing/rabbitmq-jmap-integration-testing/src/test/java/org/apache/james/jmap/rabbitmq/cucumber/awss3/RabbitMQAwsS3Stepdefs.java
  server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/ElasticSearchQuotaSearchExtension.java
Labels: waiting_merge
