Repository linagora/james-project, pull requests merged in 2020-06, with the labels that each got.

#3421 JAMES-3072 Await task completion in Mailbox Export webAdmin tests
  server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/MailboxesExportRequestToTaskTest.java
Labels: build-stability, waiting_merge

#3440 [CI_ONLY] NOREVIEW JAMES-3214 Add missing test scope
  mailbox/backup/pom.xml
  mailbox/plugin/deleted-messages-vault-cassandra/pom.xml
  mailbox/plugin/deleted-messages-vault/pom.xml
  server/protocols/webadmin/webadmin-mailbox-deleted-message-vault/pom.xml
Labels: no_review

#3469 JAMES-3267 Stop forcefully delete ImapRequestFrameDecoder.decode temporary file
  server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapRequestFrameDecoder.java
Labels: prod, waiting_merge
