Repository linagora/james-project, pull requests merged in 2020-10, with the labels that each got.

#3858 JAMES-3402 JMAP MDN messages should have a Date header
  server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/JmapMDN.java
  server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/model/JmapMDNTest.java
Labels: bug, waiting_merge

#3885 JAMES-3425 `after` is not supposed to be inclusive so fix date of mes…
  mailbox/store/src/test/java/org/apache/james/mailbox/store/search/AbstractMessageSearchIndexTest.java
Labels: contribution, waiting_merge

#3895 JAMES-3406 Detail more multi-dc setup
  docs/modules/servers/pages/distributed/architecture/consistency-model.adoc
Labels: Documentation, waiting_merge
